name: Auto Deploy to GoDaddy

on:
  push:
    branches:
      - main  # تأكد أن الفرع اللي بتشتغل عليه هو main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_dsa
          chmod 600 ~/.ssh/id_dsa
          ssh-keyscan nafsaji.net >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_dsa h5m1m38z2rcp@nafsaji.net 'cd /home/h5m1m38z2rcp/public_html && git pull origin main'
