name: Deploy to GoDaddy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no h5m1m382zrcp@127.0.0.1 -p 22 "
            cd public_html &&
            git pull origin main
          "

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa h5m1m38z2rcp@nafsaji.net "cd /home/h5m1m38z2rcp/public_html && git pull origin main"
